name: CI

# CI workflow: installs dependencies, runs typecheck, tests, and builds the app.
# If this workflow fails with 'exit code 1' inspect the job logs for the failing step.
# No secrets required for this workflow by default.

on:
  push:
    branches: [ main, copilot ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Print environment
        run: |
          node --version
          npm --version
          pwd
          ls -la
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps || npm install --legacy-peer-deps

      - name: Typecheck
        run: npm run typecheck

      - name: Run tests
        run: npm test --silent

      - name: Build
        run: npm run build
      - name: Upload build artifact (for debugging)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-diagnostics
          path: |
            .next/**
            npm-debug.log
            yarn-error.log
