name: Deploy to Netlify

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print environment
        run: |
          node --version
          npm --version
          pwd
          ls -la
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm ci --legacy-peer-deps || npm install --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=.next --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      - name: Upload build artifact (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: netlify-build-diagnostics
          path: |
            .next/**
            npm-debug.log
            yarn-error.log
